# Generated by Django 2.0.3 on 2018-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField(null=True)),
                ('boolean_field', models.BooleanField(default=False)),
                ('binary_field', models.BinaryField(null=True)),
                ('char_field', models.CharField(max_length=50, null=True)),
                ('date_field', models.DateField(null=True)),
                ('date_time_field', models.DateTimeField(null=True)),
                ('decimal_field', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('email_field', models.EmailField(max_length=254, null=True)),
                ('file_field', models.FileField(null=True, upload_to='')),
                ('file_path_field', models.FilePathField(null=True)),
                ('float_field', models.FloatField(null=True)),
                ('generic_ipaddress_field', models.GenericIPAddressField(null=True)),
                ('image_field', models.ImageField(null=True, upload_to='')),
                ('integer_field', models.IntegerField(null=True)),
                ('null_boolean_field', models.NullBooleanField()),
                ('positive_integer_field', models.PositiveIntegerField(null=True)),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(null=True)),
                ('slug_field', models.SlugField(null=True)),
                ('small_integer_field', models.SmallIntegerField(null=True)),
                ('text_field', models.TextField(null=True)),
                ('time_field', models.TimeField(null=True)),
                ('urlfield', models.URLField(null=True)),
                ('uuidfield', models.UUIDField(null=True)),
            ],
        ),
    ]
