# Generated by Django 2.0.3 on 2018-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_peewee', '0002_auto_20180310_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelWithCustomTableName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'custom_table_name',
            },
        ),
    ]
