# Generated by Django 2.0.3 on 2018-03-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_peewee', '0003_testmodelwithcustomtablename'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='text_field_with_custom_column',
            field=models.TextField(db_column='text_field_with_custom_column', null=True),
        ),
    ]
