# Generated by Django 2.0.3 on 2018-03-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_peewee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='foreign_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_django_peewee.OtherTestModel'),
        ),
    ]
