# Generated by Django 2.0.3 on 2018-03-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_peewee', '0005_auto_20180311_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_test_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_django_peewee.OtherTestModel')),
                ('test_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_django_peewee.TestModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
