# Generated by Django 2.0.3 on 2018-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_peewee', '0006_auto_20180311_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='others_models',
            field=models.ManyToManyField(related_name='test_models', through='test_django_peewee.TestThroughModel', to='test_django_peewee.OtherTestModel'),
        ),
    ]
